server:
  port: 8080 # 👈 LE PORT UNIQUE QUE REACT VA ATTAQUER

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        
        # 1. AUTHENTIFICATION (Ton service, port 8081)
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/** # 2. PROFESSEURS (Service Membre 3, port 8083)
        - id: professeur-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/professors/** # Les requêtes pour les profs (API est dans le chemin)
            
        # 3. ÉTUDIANTS (Service Membre 2, port 8082)
        - id: etudiant-service
          uri: http://localhost:8082
          predicates:
            - Path=/etudiants/** # Exemple : /etudiants/list
            
        # 4. MODULES ET NOTES (Service Membre 4, port 8084)
        - id: module-service
          uri: http://localhost:8084
          predicates:
            - Path=/modules/** # Exemple : /modules/notes/add