server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/edutrack_students
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# 1. Ensure this property is present and correctly spelled!
# Change from 'update' to 'create' (or 'create-drop')
spring.jpa.hibernate.ddl-auto=create
# Or: spring.jpa.hibernate.ddl-auto=create

spring.jpa.show-sql=true
spring.session.jdbc.initialize-schema=always